/*
**
** The C code is generated by [ATS/Postiats-0-3-12]
** The starting compilation time is: 2018-7-12: 16h:37m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/basics.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/string.dats: 1631(line=50, offs=1) -- 1670(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1629(line=50, offs=1) -- 1668(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1691(line=54, offs=1) -- 1738(line=54, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1607(line=49, offs=1) -- 1646(line=50, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1669(line=54, offs=1) -- 1715(line=55, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1738(line=59, offs=1) -- 1783(line=60, offs=38)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1865(line=66, offs=1) -- 1912(line=66, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 15937(line=927, offs=1) -- 15974(line=928, offs=30)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/array.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/SATS/jansson.sats: 991(line=28, offs=1) -- 1057(line=33, offs=3)
*/

//
#include \
"atscntrb-hx-libjansson/CATS/jansson.cats"
//
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/DATS/jansson.dats: 1394(line=38, offs=1) -- 1433(line=39, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/DATS/jansson.dats: 1456(line=43, offs=1) -- 1488(line=43, offs=33)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/SATS/jansson.sats: 991(line=28, offs=1) -- 1057(line=33, offs=3)
*/

//
#include \
"atscntrb-hx-libjansson/CATS/jansson.cats"
//
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atscntrb_jansson_json_loads)
ATSdyncst_mac(atspre_assert_errmsg_bool1)
ATSdyncst_mac(atspre_ptr_isnot_null)
ATSdyncst_mac(atscntrb_jansson_json_loadb)
ATSdyncst_mac(atspre_g1int2uint_int_size)
ATSdyncst_mac(atscntrb_jansson_json_dumps)
ATSdyncst_mac(atspre_gt_ptr1_ptr1)
ATSdyncst_mac(the_atsptr_null)
ATSdyncst_mac(atscntrb_jansson_json_decref)
ATSdyncst_mac(atscntrb_jansson_json_string)
ATSdyncst_mac(atscntrb_jansson_json_string_value)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 371(line=14, offs=1) -- 399(line=14, offs=29)
*/
ATSassume(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json) ;
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_loads(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_loadb(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_dumps(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strptr_isnot_null__3(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strptr_isnot_null__3__1(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;

#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_free(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__to_json__6(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__from_json__7(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 453(line=18, offs=22) -- 662(line=24, offs=4)
*/
/*
local: 
global: json_loads$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_loads(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref1, json_error_t) ;
ATStmpdec(tmp2, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp3) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 442(line=18, offs=11) -- 662(line=24, offs=4)
*/
ATSINSflab(__patsflab_json_loads):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 461(line=18, offs=30) -- 662(line=24, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 471(line=19, offs=6) -- 474(line=19, offs=9)
*/
/*
ATSINStmpdec(tmpref1) ;
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 508(line=20, offs=13) -- 570(line=20, offs=75)
*/
ATSINSmove(tmp2, atscntrb_jansson_json_loads(ATSPMVcastfn(strptr2string, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), ATSPMVextval(JSON_DECODE_ANY), ATSPMVrefarg1(ATSPMVptrof(tmpref1)))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 595(line=21, offs=25) -- 624(line=21, offs=54)
*/
ATSINSmove(tmp4, atspre_ptr_isnot_null(ATSPMVrefarg0(tmp2))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 580(line=21, offs=10) -- 647(line=21, offs=77)
*/
ATSINSmove_void(tmp3, atspre_assert_errmsg_bool1(tmp4, ATSPMVstring("json_loads failed."))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 653(line=23, offs=2) -- 657(line=23, offs=6)
*/
ATSINSmove(tmpret0, tmp2) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 461(line=18, offs=30) -- 662(line=24, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_loads] */

/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 693(line=26, offs=30) -- 909(line=32, offs=4)
*/
/*
local: 
global: json_loadb$1$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_loadb(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref6, json_error_t) ;
ATStmpdec(tmp7, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_size)) ;
// ATStmpdec_void(tmp9) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 674(line=26, offs=11) -- 909(line=32, offs=4)
*/
ATSINSflab(__patsflab_json_loadb):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 712(line=26, offs=49) -- 909(line=32, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 722(line=27, offs=6) -- 725(line=27, offs=9)
*/
/*
ATSINStmpdec(tmpref6) ;
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 786(line=28, offs=41) -- 795(line=28, offs=50)
*/
ATSINSmove(tmp8, atspre_g1int2uint_int_size(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 758(line=28, offs=13) -- 818(line=28, offs=73)
*/
ATSINSmove(tmp7, atscntrb_jansson_json_loadb(arg0, tmp8, ATSPMVextval(JSON_DECODE_ANY), ATSPMVrefarg1(ATSPMVptrof(tmpref6)))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 843(line=29, offs=25) -- 872(line=29, offs=54)
*/
ATSINSmove(tmp10, atspre_ptr_isnot_null(ATSPMVrefarg0(tmp7))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 828(line=29, offs=10) -- 895(line=29, offs=77)
*/
ATSINSmove_void(tmp9, atspre_assert_errmsg_bool1(tmp10, ATSPMVstring("json_loadb failed."))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 901(line=31, offs=2) -- 905(line=31, offs=6)
*/
ATSINSmove(tmpret5, tmp7) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 712(line=26, offs=49) -- 909(line=32, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret5) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_loadb] */

/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 932(line=34, offs=22) -- 1109(line=40, offs=4)
*/
/*
local: 
global: json_dumps$2$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_dumps(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp13) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp17) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 921(line=34, offs=11) -- 1109(line=40, offs=4)
*/
ATSINSflab(__patsflab_json_dumps):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 941(line=34, offs=31) -- 1109(line=40, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 957(line=35, offs=12) -- 1003(line=35, offs=58)
*/
ATSINSmove(tmp12, atscntrb_jansson_json_dumps(ATSPMVrefarg0(arg0), ATSPMVextval(JSON_ENCODE_ANY))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1030(line=36, offs=27) -- 1040(line=36, offs=37)
*/
ATSINSmove(tmp14, ATSLIB_056_prelude__strptr_isnot_null__3__1(ATSPMVrefarg0(tmp12))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1015(line=36, offs=12) -- 1062(line=36, offs=59)
*/
ATSINSmove_void(tmp13, atspre_assert_errmsg_bool1(tmp14, ATSPMVstring("json_dump failed."))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1074(line=37, offs=12) -- 1096(line=37, offs=34)
*/
ATSINSmove_void(tmp17, atscntrb_jansson_json_decref(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1102(line=39, offs=2) -- 1105(line=39, offs=5)
*/
ATSINSmove(tmpret11, tmp12) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 941(line=34, offs=31) -- 1109(line=40, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret11) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_dumps] */

#if(0)
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1986(line=72, offs=18) -- 2020(line=72, offs=52)
*/
/*
local: 
global: strptr_isnot_null$3$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strptr_isnot_null__3(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 1969(line=72, offs=1) -- 2020(line=72, offs=52)
*/
ATSINSflab(__patsflab_strptr_isnot_null):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 1995(line=72, offs=27) -- 2019(line=72, offs=51)
*/
ATSINSmove(tmpret15, atspre_gt_ptr1_ptr1(ATSPMVcastfn(strptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), the_atsptr_null)) ;

ATSfunbody_end()
ATSreturn(tmpret15) ;
} /* end of [ATSLIB_056_prelude__strptr_isnot_null__3] */
#endif // end of [TEMPLATE]

/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1986(line=72, offs=18) -- 2020(line=72, offs=52)
*/
/*
local: 
global: strptr_isnot_null$3$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__strptr_isnot_null__3__1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15__1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 1969(line=72, offs=1) -- 2020(line=72, offs=52)
*/
ATSINSflab(__patsflab_strptr_isnot_null):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats({$PATSPRE}/DATS/strptr.dats): 1995(line=72, offs=27) -- 2019(line=72, offs=51)
*/
ATSINSmove(tmpret15__1, atspre_gt_ptr1_ptr1(ATSPMVcastfn(strptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), the_atsptr_null)) ;

ATSfunbody_end()
ATSreturn(tmpret15__1) ;
} /* end of [ATSLIB_056_prelude__strptr_isnot_null__3__1] */

/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 1131(line=42, offs=21) -- 1162(line=42, offs=52)
*/
/*
local: 
global: json_free$5$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_free(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret18) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1121(line=42, offs=11) -- 1162(line=42, offs=52)
*/
ATSINSflab(__patsflab_json_free):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1140(line=42, offs=30) -- 1162(line=42, offs=52)
*/
ATSINSmove_void(tmpret18, atscntrb_jansson_json_decref(arg0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret18) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_free] */

#if(0)
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 1190(line=44, offs=27) -- 1335(line=49, offs=4)
*/
/*
local: 
global: to_json$6$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = S2Ecst(string_type)
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__to_json__6(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp20, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp21) ;
ATStmpdec(tmp22, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1174(line=44, offs=11) -- 1335(line=49, offs=4)
*/
ATSINSflab(__patsflab_to_json):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1198(line=44, offs=35) -- 1335(line=49, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1215(line=45, offs=13) -- 1236(line=45, offs=34)
*/
ATSINSmove(tmp20, atscntrb_jansson_json_string(arg0)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1264(line=46, offs=28) -- 1293(line=46, offs=57)
*/
ATSINSmove(tmp22, atspre_ptr_isnot_null(ATSPMVrefarg0(tmp20))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1249(line=46, offs=13) -- 1321(line=46, offs=85)
*/
ATSINSmove_void(tmp21, atspre_assert_errmsg_bool1(tmp22, ATSPMVstring("to_json<string> failed."))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1327(line=48, offs=2) -- 1331(line=48, offs=6)
*/
ATSINSmove(tmpret19, tmp20) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1198(line=44, offs=35) -- 1335(line=49, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret19) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__to_json__6] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 1366(line=51, offs=30) -- 1495(line=57, offs=4)
*/
/*
local: 
global: from_json$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = S2Eexi(l(4274); S2Eapp(S2Ecst(>); S2Evar(l(4274)), S2Ecst(null)); S2Eapp(S2Ecst(strptr_addr_vtype); S2Evar(l(4274))))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__from_json__7(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret23, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp24, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1347(line=51, offs=11) -- 1495(line=57, offs=4)
*/
ATSINSflab(__patsflab_from_json):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1375(line=51, offs=39) -- 1495(line=57, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1396(line=52, offs=17) -- 1424(line=52, offs=45)
*/
ATSINSmove(tmp24, atscntrb_jansson_json_string_value(ATSPMVrefarg0(arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1436(line=53, offs=12) -- 1442(line=53, offs=18)
*/
ATSINSmove(tmpret23, PMVtmpltcst(strptr1_copy<>)(ATSPMVrefarg0(tmp24))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/json.dats: 1375(line=51, offs=39) -- 1495(line=57, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret23) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__from_json__7] */
#endif // end of [TEMPLATE]

#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/* in of [local] */
/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]

/* ****** ****** */

/* end-of-compilation-unit */
