/*
**
** The C code is generated by [ATS/Postiats-0-3-12]
** The starting compilation time is: 2018-7-12: 16h:37m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/basics.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/string.dats: 1631(line=50, offs=1) -- 1670(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1629(line=50, offs=1) -- 1668(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1691(line=54, offs=1) -- 1738(line=54, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1607(line=49, offs=1) -- 1646(line=50, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1669(line=54, offs=1) -- 1715(line=55, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1738(line=59, offs=1) -- 1783(line=60, offs=38)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1865(line=66, offs=1) -- 1912(line=66, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 15937(line=927, offs=1) -- 15974(line=928, offs=30)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/array.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/transport.sats: 1(line=1, offs=1) -- 24(line=1, offs=24)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 92(line=8, offs=1) -- 118(line=8, offs=27)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/transport.sats: 1(line=1, offs=1) -- 24(line=1, offs=24)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 119(line=9, offs=1) -- 140(line=9, offs=22)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 141(line=10, offs=1) -- 164(line=10, offs=24)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 166(line=12, offs=1) -- 205(line=12, offs=40)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 206(line=13, offs=1) -- 231(line=13, offs=26)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 28(line=3, offs=1) -- 49(line=3, offs=22)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 119(line=8, offs=1) -- 193(line=8, offs=75)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/SATS/jansson.sats: 991(line=28, offs=1) -- 1057(line=33, offs=3)
*/

//
#include \
"atscntrb-hx-libjansson/CATS/jansson.cats"
//
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 194(line=9, offs=1) -- 268(line=9, offs=75)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/DATS/jansson.dats: 1394(line=38, offs=1) -- 1433(line=39, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/DATS/jansson.dats: 1456(line=43, offs=1) -- 1488(line=43, offs=33)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/SATS/jansson.sats: 991(line=28, offs=1) -- 1057(line=33, offs=3)
*/

//
#include \
"atscntrb-hx-libjansson/CATS/jansson.cats"
//
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 269(line=10, offs=1) -- 310(line=10, offs=42)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 232(line=14, offs=1) -- 259(line=14, offs=28)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/thread.dats: 57(line=7, offs=1) -- 80(line=7, offs=24)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 28(line=3, offs=1) -- 49(line=3, offs=22)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 119(line=8, offs=1) -- 193(line=8, offs=75)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/SATS/jansson.sats: 991(line=28, offs=1) -- 1057(line=33, offs=3)
*/

//
#include \
"atscntrb-hx-libjansson/CATS/jansson.cats"
//
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 194(line=9, offs=1) -- 268(line=9, offs=75)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/DATS/jansson.dats: 1394(line=38, offs=1) -- 1433(line=39, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/DATS/jansson.dats: 1456(line=43, offs=1) -- 1488(line=43, offs=33)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/SATS/jansson.sats: 991(line=28, offs=1) -- 1057(line=33, offs=3)
*/

//
#include \
"atscntrb-hx-libjansson/CATS/jansson.cats"
//
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 269(line=10, offs=1) -- 310(line=10, offs=42)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/thread.dats: 57(line=7, offs=1) -- 80(line=7, offs=24)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/unistd.sats: 1395(line=36, offs=1) -- 1443(line=39, offs=3)
*/

#include \
"libats/libc/CATS/unistd.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/unistd.sats: 1803(line=61, offs=1) -- 1852(line=63, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/main.dats: 39(line=3, offs=1) -- 124(line=7, offs=3)
*/
ATSextcode_beg()
#include <nng/nng.h>
#include <nng/protocol/bus0/bus.h>
#include <uuid/uuid.h>
ATSextcode_end()
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_generate, (), atstkind_type(atstype_ptrk)) ;
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_copy, (atsrefarg0_type(atstkind_type(atstype_ptrk))), atstkind_type(atstype_ptrk)) ;
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_unparse, (atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg1_type(atstyarr_type(atstkind_t0ype(atstype_char)))), atsvoid_t0ype) ;
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_parse, (atsrefarg1_type(atstyarr_type(atstkind_t0ype(atstype_char)))), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(atspre_print_bool)
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_equal, (atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg0_type(atstkind_type(atstype_ptrk))), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_free, (atstkind_type(atstype_ptrk)), atsvoid_t0ype) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/Users/hwwu/Git/ats-sessions/ats/main.dats: 364(line=20, offs=17) -- 1846(line=79, offs=4)
*/
/*
local: 
global: mainats_void_0$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref3[37], atstkind_t0ype(atstype_char)) ;
// ATStmpdec_void(tmp4) ;
// ATStmpdec_void(tmp5) ;
// ATStmpdec_void(tmp6) ;
ATStmpdec(tmp7, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp8) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp10) ;
// ATStmpdec_void(tmp11) ;
// ATStmpdec_void(tmp12) ;
// ATStmpdec_void(tmp13) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 358(line=20, offs=11) -- 1846(line=79, offs=4)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 369(line=20, offs=22) -- 1846(line=79, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 388(line=22, offs=14) -- 404(line=22, offs=30)
*/
ATSINSmove(tmp1, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_generate()) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 418(line=23, offs=14) -- 433(line=23, offs=29)
*/
ATSINSmove(tmp2, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_copy(ATSPMVrefarg0(tmp1))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 440(line=25, offs=6) -- 447(line=25, offs=13)
*/
/*
ATSINStmpdec(tmpref3) ;
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 471(line=26, offs=11) -- 500(line=26, offs=40)
*/
ATSINSmove_void(tmp4, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_unparse(ATSPMVrefarg0(tmp2), ATSPMVrefarg1(ATSPMVptrof(tmpref3[0])))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 511(line=28, offs=10) -- 550(line=28, offs=49)
*/
ATSINSmove_void(tmp5, atspre_print_string(ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmpref3))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 511(line=28, offs=10) -- 550(line=28, offs=49)
*/
ATSINSmove_void(tmp6, atspre_print_newline()) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 564(line=29, offs=14) -- 582(line=29, offs=32)
*/
ATSINSmove(tmp7, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_parse(ATSPMVrefarg1(ATSPMVptrof(tmpref3[0])))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 603(line=31, offs=20) -- 628(line=31, offs=45)
*/
ATSINSmove(tmp9, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_equal(ATSPMVrefarg0(tmp1), ATSPMVrefarg0(tmp7))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 593(line=31, offs=10) -- 629(line=31, offs=46)
*/
ATSINSmove_void(tmp8, atspre_print_bool(tmp9)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 593(line=31, offs=10) -- 629(line=31, offs=46)
*/
ATSINSmove_void(tmp10, atspre_print_newline()) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 641(line=34, offs=10) -- 656(line=34, offs=25)
*/
ATSINSmove_void(tmp11, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_free(tmp1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 667(line=35, offs=10) -- 682(line=35, offs=25)
*/
ATSINSmove_void(tmp12, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_free(tmp2)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 692(line=36, offs=10) -- 707(line=36, offs=25)
*/
ATSINSmove_void(tmp13, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_free(tmp7)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 1839(line=78, offs=1) -- 1846(line=79, offs=4)
*/
ATSINSmove_void(tmpret0, ATSPMVempty()) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/main.dats: 369(line=20, offs=22) -- 1846(line=79, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_main_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_main_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_main_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_main_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_main_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_main_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
