/*
**
** The C code is generated by [ATS/Postiats-0-3-12]
** The starting compilation time is: 2018-7-12: 16h:37m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/basics.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/string.dats: 1631(line=50, offs=1) -- 1670(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1629(line=50, offs=1) -- 1668(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1691(line=54, offs=1) -- 1738(line=54, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1607(line=49, offs=1) -- 1646(line=50, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1669(line=54, offs=1) -- 1715(line=55, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1738(line=59, offs=1) -- 1783(line=60, offs=38)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1865(line=66, offs=1) -- 1912(line=66, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 15937(line=927, offs=1) -- 15974(line=928, offs=30)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/array.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/thread.dats: 28(line=3, offs=1) -- 55(line=5, offs=3)
*/
ATSextcode_beg()
#include <pthread.h>
ATSextcode_end()
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_cloptr_free)
ATSdyncst_mac(the_atsptr_null)
ATSdyncst_mac(pthread_create)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_neq_int)
ATSdyncst_mac(atspre_assert_errmsg_bool0)
ATSdyncst_mac(atspre_g0int_eq_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
/*
/Users/hwwu/Git/ats-sessions/ats/thread.dats: 169(line=14, offs=1) -- 191(line=14, offs=23)
*/
ATSassume(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__tid) ;
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
ATSextern()
pthread_t
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__thread_self() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
pthread_t
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__thread_spawn(atstype_cloptr) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_type(atstype_ptrk)
apply_2(atstype_cloptr) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__neq_g0int_int__3(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__neq_g0int_int__3__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__thread_join(pthread_t) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/Users/hwwu/Git/ats-sessions/ats/thread.dats: 220(line=18, offs=23) -- 258(line=19, offs=33)
*/
/*
local: 
global: thread_self$0$0(level=0)
local: 
global: 
*/
ATSextern()
pthread_t
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__thread_self()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, pthread_t) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 208(line=18, offs=11) -- 258(line=19, offs=33)
*/
ATSINSflab(__patsflab_thread_self):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 227(line=19, offs=2) -- 258(line=19, offs=33)
*/
ATSINSmove(tmpret0, ATSextfcall(pthread_self, ())) ;
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__thread_self] */

/*
/Users/hwwu/Git/ats-sessions/ats/thread.dats: 283(line=21, offs=24) -- 952(line=47, offs=4)
*/
/*
local: 
global: thread_spawn$1$0(level=0)
local: 
global: 
*/
ATSextern()
pthread_t
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__thread_spawn(atstype_cloptr arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, pthread_t) ;
ATStmpdec(tmpref5, pthread_t) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp12) ;
// ATStmpdec_void(tmp13) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 270(line=21, offs=11) -- 952(line=47, offs=4)
*/
ATSINSflab(__patsflab_thread_spawn):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 289(line=21, offs=30) -- 952(line=47, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 648(line=35, offs=6) -- 651(line=35, offs=9)
*/
/*
ATSINStmpdec(tmpref5) ;
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 702(line=37, offs=12) -- 735(line=37, offs=45)
*/
ATSINSmove(tmp6, pthread_create(ATSPMVrefarg1(ATSPMVptrof(tmpref5)), ATSPMVi0nt(0), ATSPMVfunlab(apply_2), arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 744(line=39, offs=5) -- 752(line=39, offs=13)
*/
ATSINSmove(tmp7, ATSLIB_056_prelude__neq_g0int_int__3__1(tmp6, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 741(line=39, offs=2) -- 948(line=46, offs=14)
*/
ATSif(
tmp7
) ATSthen() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 759(line=40, offs=7) -- 890(line=43, offs=14)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 775(line=41, offs=12) -- 813(line=41, offs=50)
*/
ATSINSmove_void(tmp12, atspre_cloptr_free(ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0))))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 840(line=42, offs=27) -- 847(line=42, offs=34)
*/
ATSINSmove(tmp14, ATSLIB_056_prelude__eq_g0int_int__7__1(tmp6, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 825(line=42, offs=12) -- 876(line=42, offs=63)
*/
ATSINSmove_void(tmp13, atspre_assert_errmsg_bool0(tmp14, ATSPMVstring("thread_spawn_env: failed"))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 883(line=43, offs=7) -- 886(line=43, offs=10)
*/
ATSINSmove(tmpret1, tmpref5) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 759(line=40, offs=7) -- 890(line=43, offs=14)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 897(line=44, offs=7) -- 948(line=46, offs=14)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 941(line=46, offs=7) -- 944(line=46, offs=10)
*/
ATSINSmove(tmpret1, tmpref5) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 897(line=44, offs=7) -- 948(line=46, offs=14)
*/
/*
INSletpop()
*/
} /* ATSendif */
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 289(line=21, offs=30) -- 952(line=47, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__thread_spawn] */

/*
/Users/hwwu/Git/ats-sessions/ats/thread.dats: 341(line=24, offs=6) -- 474(line=29, offs=5)
*/
/*
local: 
global: apply_2$0(level=1)
local: 
global: 
*/
ATSstatic()
atstkind_type(atstype_ptrk)
apply_2(atstype_cloptr arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp3) ;
// ATStmpdec_void(tmp4) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 341(line=24, offs=6) -- 474(line=29, offs=5)
*/
ATSINSflab(__patsflab_apply_2):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 381(line=24, offs=46) -- 474(line=29, offs=5)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 396(line=25, offs=11) -- 400(line=25, offs=15)
*/
ATSINSmove_void(tmp3, ATSfunclo_clo(ATSPMVrefarg0(arg0), (atstype_cloptr), atsvoid_t0ype)(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 411(line=26, offs=11) -- 449(line=26, offs=49)
*/
ATSINSmove_void(tmp4, atspre_cloptr_free(ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 457(line=28, offs=3) -- 469(line=28, offs=15)
*/
ATSINSmove(tmpret2, the_atsptr_null) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 381(line=24, offs=46) -- 474(line=29, offs=5)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [apply_2] */

#if(0)
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 12337(line=639, offs=3) -- 12377(line=639, offs=43)
*/
/*
local: 
global: neq_g0int_int$3$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4625)
tmparg = S2Evar(tk(4625))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__neq_g0int_int__3(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12321(line=638, offs=1) -- 12377(line=639, offs=43)
*/
ATSINSflab(__patsflab_neq_g0int_int):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12364(line=639, offs=30) -- 12375(line=639, offs=41)
*/
ATSINSmove(tmp9, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4625))>)(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12346(line=639, offs=12) -- 12377(line=639, offs=43)
*/
ATSINSmove(tmpret8, PMVtmpltcst(g0int_neq<S2Evar(tk(4625))>)(arg0, tmp9)) ;

ATSfunbody_end()
ATSreturn(tmpret8) ;
} /* end of [ATSLIB_056_prelude__neq_g0int_int__3] */
#endif // end of [TEMPLATE]

/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 12337(line=639, offs=3) -- 12377(line=639, offs=43)
*/
/*
local: 
global: neq_g0int_int$3$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4625)
tmparg = S2Evar(tk(4625))
tmpsub = Some(tk(4625) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__neq_g0int_int__3__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp9__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12321(line=638, offs=1) -- 12377(line=639, offs=43)
*/
ATSINSflab(__patsflab_neq_g0int_int):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12364(line=639, offs=30) -- 12375(line=639, offs=41)
*/
ATSINSmove(tmp9__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12346(line=639, offs=12) -- 12377(line=639, offs=43)
*/
ATSINSmove(tmpret8__1, atspre_g0int_neq_int(arg0, tmp9__1)) ;

ATSfunbody_end()
ATSreturn(tmpret8__1) ;
} /* end of [ATSLIB_056_prelude__neq_g0int_int__3__1] */

#if(0)
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4624)
tmparg = S2Evar(tk(4624))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp16, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4624))>)(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret15, PMVtmpltcst(g0int_eq<S2Evar(tk(4624))>)(arg0, tmp16)) ;

ATSfunbody_end()
ATSreturn(tmpret15) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__7] */
#endif // end of [TEMPLATE]

/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$7$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4624)
tmparg = S2Evar(tk(4624))
tmpsub = Some(tk(4624) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp16__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp16__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret15__1, atspre_g0int_eq_int(arg0, tmp16__1)) ;

ATSfunbody_end()
ATSreturn(tmpret15__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__7__1] */

/*
/Users/hwwu/Git/ats-sessions/ats/thread.dats: 976(line=49, offs=23) -- 1095(line=53, offs=4)
*/
/*
local: 
global: thread_join$10$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__thread_join(pthread_t arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret19) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 964(line=49, offs=11) -- 1095(line=53, offs=4)
*/
ATSINSflab(__patsflab_thread_join):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 984(line=49, offs=31) -- 1095(line=53, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 1000(line=50, offs=12) -- 1039(line=50, offs=51)
*/
ATSINSmove(tmp20, ATSextfcall(pthread_join, (arg0, ATSPMVi0nt(0)))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 1060(line=52, offs=17) -- 1067(line=52, offs=24)
*/
ATSINSmove(tmp21, ATSLIB_056_prelude__eq_g0int_int__7__2(tmp20, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 1045(line=52, offs=2) -- 1091(line=52, offs=48)
*/
ATSINSmove_void(tmpret19, atspre_assert_errmsg_bool0(tmp21, ATSPMVstring("thread_join failed."))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/thread.dats: 984(line=49, offs=31) -- 1095(line=53, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret19) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__thread_join] */

/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$7$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4624)
tmparg = S2Evar(tk(4624))
tmpsub = Some(tk(4624) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp16__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp16__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret15__2, atspre_g0int_eq_int(arg0, tmp16__2)) ;

ATSfunbody_end()
ATSreturn(tmpret15__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__7__2] */

#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/* in of [local] */
/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]

/* ****** ****** */

/* end-of-compilation-unit */
