/*
**
** The C code is generated by [ATS/Postiats-0-3-12]
** The starting compilation time is: 2018-7-12: 16h:37m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/transport.sats: 1(line=1, offs=1) -- 24(line=1, offs=24)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 28(line=3, offs=1) -- 49(line=3, offs=22)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 119(line=8, offs=1) -- 193(line=8, offs=75)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/SATS/jansson.sats: 991(line=28, offs=1) -- 1057(line=33, offs=3)
*/

//
#include \
"atscntrb-hx-libjansson/CATS/jansson.cats"
//
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 194(line=9, offs=1) -- 268(line=9, offs=75)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/DATS/jansson.dats: 1394(line=38, offs=1) -- 1433(line=39, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/DATS/jansson.dats: 1456(line=43, offs=1) -- 1488(line=43, offs=33)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/atscntrb/atscntrb-hx-libjansson/SATS/jansson.sats: 991(line=28, offs=1) -- 1057(line=33, offs=3)
*/

//
#include \
"atscntrb-hx-libjansson/CATS/jansson.cats"
//
/*
/Users/hwwu/Git/ats-sessions/ats/json.dats: 269(line=10, offs=1) -- 310(line=10, offs=42)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/thread.dats: 57(line=7, offs=1) -- 80(line=7, offs=24)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/basics.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/string.dats: 1631(line=50, offs=1) -- 1670(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1629(line=50, offs=1) -- 1668(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1691(line=54, offs=1) -- 1738(line=54, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1607(line=49, offs=1) -- 1646(line=50, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1669(line=54, offs=1) -- 1715(line=55, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1738(line=59, offs=1) -- 1783(line=60, offs=38)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1865(line=66, offs=1) -- 1912(line=66, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 15937(line=927, offs=1) -- 15974(line=928, offs=30)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/array.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 28(line=3, offs=1) -- 90(line=6, offs=3)
*/
ATSextcode_beg()
#include <nng/nng.h>
#include <nng/protocol/bus0/bus.h>
ATSextcode_end()
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
pthread_t atslab__0 ;
atstkind_type(atstype_ptrk) atslab__1 ;
} postiats_tyrec_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_ptr_alloc_tsz)
ATSdyncst_mac(nng_bus0_open)
ATSdyncst_mac(atspre_assert_errmsg_bool0)
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__from_nng_socket, (nng_socket), atstkind_type(atstype_ptrk)) ;
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__to_nng_socket, (atsrefarg0_type(atstkind_type(atstype_ptrk))), nng_socket) ;
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_dumps, (atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(atspre_strptr_free)
ATSdyncst_mac(nng_recv)
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_loadb, (atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(atspre_g1uint2int_size_int)
ATSdyncst_mac(nng_free)
ATSdyncst_mac(nng_bus0_open_raw)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__thread_spawn, (atstype_cloptr), pthread_t) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 2471(line=89, offs=1) -- 2520(line=91, offs=3)
*/
ATSextcode_beg()
	nng_socket empty = NNG_SOCKET_INITIALIZER;
ATSextcode_end()
#if(0)
ATSextern()
nng_socket
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__to_nng_socket(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__from_nng_socket(nng_socket) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ref_make_elt__3(atstyvar_type(a)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ref_make_elt__3__1(nng_socket) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr_alloc__5() ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr_alloc__5__1() ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_make__7() ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_term__8(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_listen__9(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_connect__10(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_send__11(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_recv__12(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSextern()
postiats_tyrec_0
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_nn_broker(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atsvoid_t0ype
__patsfun_19(nng_socket, nng_socket) ;

ATSclosurerize_beg(__patsfun_19, (nng_socket, nng_socket), (), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
nng_socket env0 ;
nng_socket env1 ;
} __patsfun_19__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
__patsfun_19__cfun
(
__patsfun_19__closure_t0ype *p_cenv
)
{
ATSFCreturn_void(__patsfun_19(p_cenv->env0, p_cenv->env1)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_19__closureinit
(
__patsfun_19__closure_t0ype *p_cenv, nng_socket env0, nng_socket env1
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->cfun = __patsfun_19__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_19__closurerize
(
nng_socket env0, nng_socket env1
)
{
return __patsfun_19__closureinit(ATS_MALLOC(sizeof(__patsfun_19__closure_t0ype)), env0, env1) ;
} /* end of [closurerize] */
ATSclosurerize_end()
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 501(line=24, offs=25) -- 542(line=24, offs=66)
*/
/*
local: 
global: to_nng_socket$0$0(level=0)
local: 
global: 
*/
ATSextern()
nng_socket
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__to_nng_socket(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, nng_socket) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 487(line=24, offs=11) -- 542(line=24, offs=66)
*/
ATSINSflab(__patsflab_to_nng_socket):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 507(line=24, offs=31) -- 542(line=24, offs=66)
*/
ATSINSmove(tmpret0, ATSderef(ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), nng_socket)) ;
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__to_nng_socket] */

/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 631(line=27, offs=27) -- 690(line=27, offs=86)
*/
/*
local: 
global: from_nng_socket$1$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__from_nng_socket(nng_socket arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 615(line=27, offs=11) -- 690(line=27, offs=86)
*/
ATSINSflab(__patsflab_from_nng_socket):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 669(line=27, offs=65) -- 689(line=27, offs=85)
*/
ATSINSmove(tmp2, ATSLIB_056_prelude__ref_make_elt__3__1(arg0)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 640(line=27, offs=36) -- 690(line=27, offs=86)
*/
ATSINSmove(tmpret1, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp2)) ;
ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__from_nng_socket] */

#if(0)
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats: 1613(line=51, offs=3) -- 1748(line=60, offs=4)
*/
/*
local: 
global: ref_make_elt$3$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(5435)
tmparg = S2Evar(a(5435))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ref_make_elt__3(atstyvar_type(a) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp4, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1598(line=50, offs=1) -- 1748(line=60, offs=4)
*/
ATSINSflab(__patsflab_ref_make_elt):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1620(line=51, offs=10) -- 1748(line=60, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1647(line=54, offs=17) -- 1661(line=54, offs=31)
*/
ATSINSmove(tmp4, PMVtmpltcst(ptr_alloc<S2Evar(a(5435))>)()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1703(line=58, offs=3) -- 1711(line=58, offs=11)
*/
ATSINSstore(ATSderef(tmp4, atstyvar_type(a)), arg0) ;
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1715(line=59, offs=3) -- 1744(line=59, offs=32)
*/
ATSINSmove(tmpret3, ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), tmp4)) ;
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1620(line=51, offs=10) -- 1748(line=60, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [ATSLIB_056_prelude__ref_make_elt__3] */
#endif // end of [TEMPLATE]

/*
/Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats: 1613(line=51, offs=3) -- 1748(line=60, offs=4)
*/
/*
local: 
global: ref_make_elt$3$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(5435)
tmparg = S2Evar(a(5435))
tmpsub = Some(a(5435) -> S2Eextype(nng_socket))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ref_make_elt__3__1(nng_socket arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp4__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1598(line=50, offs=1) -- 1748(line=60, offs=4)
*/
ATSINSflab(__patsflab_ref_make_elt):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1620(line=51, offs=10) -- 1748(line=60, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1647(line=54, offs=17) -- 1661(line=54, offs=31)
*/
ATSINSmove(tmp4__1, ATSLIB_056_prelude__ptr_alloc__5__1()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1703(line=58, offs=3) -- 1711(line=58, offs=11)
*/
ATSINSstore(ATSderef(tmp4__1, nng_socket), arg0) ;
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1715(line=59, offs=3) -- 1744(line=59, offs=32)
*/
ATSINSmove(tmpret3__1, ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), tmp4__1)) ;
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/reference.dats({$PATSPRE}/DATS/reference.dats): 1620(line=51, offs=10) -- 1748(line=60, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret3__1) ;
} /* end of [ATSLIB_056_prelude__ref_make_elt__3__1] */

#if(0)
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats: 3717(line=184, offs=10) -- 3749(line=184, offs=42)
*/
/*
local: 
global: ptr_alloc$5$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(4750)
tmparg = S2Evar(a(4750))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr_alloc__5()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 3708(line=184, offs=1) -- 3749(line=184, offs=42)
*/
ATSINSflab(__patsflab_ptr_alloc):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 3722(line=184, offs=15) -- 3749(line=184, offs=42)
*/
ATSINSmove(tmpret7, atspre_ptr_alloc_tsz(ATSPMVsizeof(atstyvar_type(a)))) ;

ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [ATSLIB_056_prelude__ptr_alloc__5] */
#endif // end of [TEMPLATE]

/*
/Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats: 3717(line=184, offs=10) -- 3749(line=184, offs=42)
*/
/*
local: 
global: ptr_alloc$5$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(4750)
tmparg = S2Evar(a(4750))
tmpsub = Some(a(4750) -> S2Eextype(nng_socket))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr_alloc__5__1()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 3708(line=184, offs=1) -- 3749(line=184, offs=42)
*/
ATSINSflab(__patsflab_ptr_alloc):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 3722(line=184, offs=15) -- 3749(line=184, offs=42)
*/
ATSINSmove(tmpret7__1, atspre_ptr_alloc_tsz(ATSPMVsizeof(nng_socket))) ;

ATSfunbody_end()
ATSreturn(tmpret7__1) ;
} /* end of [ATSLIB_056_prelude__ptr_alloc__5__1] */

#if(0)
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 750(line=31, offs=26) -- 987(line=38, offs=4)
*/
/*
local: 
global: trans_make$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = S2Eapp(S2Ecst(nn); )
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_make__7()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref10, nng_socket) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp12) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 735(line=31, offs=11) -- 987(line=38, offs=4)
*/
ATSINSflab(__patsflab_trans_make):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 755(line=31, offs=31) -- 987(line=38, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 765(line=32, offs=6) -- 769(line=32, offs=10)
*/
/*
ATSINStmpdec(tmpref10) ;
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 872(line=34, offs=12) -- 890(line=34, offs=30)
*/
ATSINSmove(tmp11, nng_bus0_open(ATSPMVrefarg1(ATSPMVptrof(tmpref10)))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 917(line=35, offs=27) -- 924(line=35, offs=34)
*/
ATSINSmove(tmp13, PMVtmpltcst(eq_g0int_int<S2Eextkind(atstype_int)>)(tmp11, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 902(line=35, offs=12) -- 957(line=35, offs=67)
*/
ATSINSmove_void(tmp12, atspre_assert_errmsg_bool0(tmp13, ATSPMVstring("trans_make (nanomsg) failed."))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 963(line=37, offs=2) -- 983(line=37, offs=22)
*/
ATSINSmove(tmpret9, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__from_nng_socket(tmpref10)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 755(line=31, offs=31) -- 987(line=38, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret9) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_make__7] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 1014(line=40, offs=26) -- 1180(line=45, offs=4)
*/
/*
local: 
global: trans_term$8$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = S2Eapp(S2Ecst(nn); )
tmpsub = None()
*/
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_term__8(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret14) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp16, nng_socket) ;
// ATStmpdec_void(tmp17) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 999(line=40, offs=11) -- 1180(line=45, offs=4)
*/
ATSINSflab(__patsflab_trans_term):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1020(line=40, offs=32) -- 1180(line=45, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1065(line=41, offs=41) -- 1080(line=41, offs=56)
*/
ATSINSmove(tmp16, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__to_nng_socket(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1036(line=41, offs=12) -- 1081(line=41, offs=57)
*/
ATSINSmove(tmp15, ATSextfcall(nng_close, (tmp16))) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1108(line=42, offs=27) -- 1115(line=42, offs=34)
*/
ATSINSmove(tmp18, PMVtmpltcst(eq_g0int_int<S2Eextkind(atstype_int)>)(tmp15, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1093(line=42, offs=12) -- 1149(line=42, offs=68)
*/
ATSINSmove_void(tmp17, atspre_assert_errmsg_bool0(tmp18, ATSPMVstring("trans_close (nanomsg) failed."))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1155(line=44, offs=2) -- 1176(line=44, offs=23)
*/
ATSINSmove_void(tmpret14, ATSPMVcastfn(castvwtp0, atsvoid_t0ype, arg0)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1020(line=40, offs=32) -- 1180(line=45, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret14) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_term__8] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 1209(line=47, offs=28) -- 1372(line=51, offs=4)
*/
/*
local: 
global: trans_listen$9$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = S2Eapp(S2Ecst(nn); )
tmpsub = None()
*/
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_listen__9(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret19) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp21, nng_socket) ;
// ATStmpdec_void(tmp22) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1192(line=47, offs=11) -- 1372(line=51, offs=4)
*/
ATSINSflab(__patsflab_trans_listen):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1221(line=47, offs=40) -- 1372(line=51, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1267(line=48, offs=42) -- 1282(line=48, offs=57)
*/
ATSINSmove(tmp21, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__to_nng_socket(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1237(line=48, offs=12) -- 1295(line=48, offs=70)
*/
ATSINSmove(tmp20, ATSextfcall(nng_listen, (tmp21, arg1, ATSPMVi0nt(0), ATSPMVi0nt(0)))) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1322(line=49, offs=27) -- 1329(line=49, offs=34)
*/
ATSINSmove(tmp23, PMVtmpltcst(eq_g0int_int<S2Eextkind(atstype_int)>)(tmp20, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1307(line=49, offs=12) -- 1364(line=49, offs=69)
*/
ATSINSmove_void(tmp22, atspre_assert_errmsg_bool0(tmp23, ATSPMVstring("trans_listen (nanomsg) failed."))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1365(line=50, offs=1) -- 1372(line=51, offs=4)
*/
ATSINSmove_void(tmpret19, ATSPMVempty()) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1221(line=47, offs=40) -- 1372(line=51, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret19) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_listen__9] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 1402(line=53, offs=29) -- 1564(line=57, offs=4)
*/
/*
local: 
global: trans_connect$10$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = S2Eapp(S2Ecst(nn); )
tmpsub = None()
*/
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_connect__10(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret24) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp26, nng_socket) ;
// ATStmpdec_void(tmp27) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1384(line=53, offs=11) -- 1564(line=57, offs=4)
*/
ATSINSflab(__patsflab_trans_connect):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1414(line=53, offs=41) -- 1564(line=57, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1458(line=54, offs=40) -- 1473(line=54, offs=55)
*/
ATSINSmove(tmp26, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__to_nng_socket(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1430(line=54, offs=12) -- 1486(line=54, offs=68)
*/
ATSINSmove(tmp25, ATSextfcall(nng_dial, (tmp26, arg1, ATSPMVi0nt(0), ATSPMVi0nt(0)))) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1513(line=55, offs=27) -- 1520(line=55, offs=34)
*/
ATSINSmove(tmp28, PMVtmpltcst(eq_g0int_int<S2Eextkind(atstype_int)>)(tmp25, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1498(line=55, offs=12) -- 1556(line=55, offs=70)
*/
ATSINSmove_void(tmp27, atspre_assert_errmsg_bool0(tmp28, ATSPMVstring("trans_connect (nanomsg) failed."))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1557(line=56, offs=1) -- 1564(line=57, offs=4)
*/
ATSINSmove_void(tmpret24, ATSPMVempty()) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1414(line=53, offs=41) -- 1564(line=57, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret24) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_connect__10] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 1597(line=59, offs=32) -- 1844(line=66, offs=4)
*/
/*
local: 
global: trans_send$11$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = S2Ecst(json); S2Eapp(S2Ecst(nn); )
tmpsub = None()
*/
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_send__11(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret29) ;
ATStmpdec(tmp30, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp31, atstkind_t0ype(atstype_ssize)) ;
ATStmpdec(tmp32, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp33, nng_socket) ;
// ATStmpdec_void(tmp34) ;
ATStmpdec(tmp35, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp36) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1576(line=59, offs=11) -- 1844(line=66, offs=4)
*/
ATSINSflab(__patsflab_trans_send):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1609(line=59, offs=44) -- 1844(line=66, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1625(line=60, offs=12) -- 1640(line=60, offs=27)
*/
ATSINSmove(tmp30, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_dumps(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1652(line=61, offs=12) -- 1662(line=61, offs=22)
*/
ATSINSmove(tmp31, PMVtmpltcst(strptr_length<>)(ATSPMVrefarg0(tmp30))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1702(line=62, offs=40) -- 1717(line=62, offs=55)
*/
ATSINSmove(tmp33, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__to_nng_socket(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1674(line=62, offs=12) -- 1749(line=62, offs=87)
*/
ATSINSmove(tmp32, ATSextfcall(nng_send, (tmp33, ATSPMVcastfn(strptr2string, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp30)), tmp31, ATSPMVi0nt(0)))) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1776(line=63, offs=27) -- 1783(line=63, offs=34)
*/
ATSINSmove(tmp35, PMVtmpltcst(eq_g0int_int<S2Eextkind(atstype_int)>)(tmp32, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1761(line=63, offs=12) -- 1816(line=63, offs=67)
*/
ATSINSmove_void(tmp34, atspre_assert_errmsg_bool0(tmp35, ATSPMVstring("trans_send (nanomsg) failed."))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1828(line=64, offs=12) -- 1836(line=64, offs=20)
*/
ATSINSmove_void(tmp36, atspre_strptr_free(tmp30)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1837(line=65, offs=1) -- 1844(line=66, offs=4)
*/
ATSINSmove_void(tmpret29, ATSPMVempty()) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1609(line=59, offs=44) -- 1844(line=66, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret29) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_send__11] */
#endif // end of [TEMPLATE]

#if(0)
/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 1877(line=68, offs=32) -- 2469(line=87, offs=4)
*/
/*
local: 
global: trans_recv$12$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = S2Ecst(json); S2Eapp(S2Ecst(nn); )
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_recv__12(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret37, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref38, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref39, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp40, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp41, nng_socket) ;
// ATStmpdec_void(tmp42) ;
ATStmpdec(tmp43, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp44, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp45, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp46) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1856(line=68, offs=11) -- 2469(line=87, offs=4)
*/
ATSINSflab(__patsflab_trans_recv):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1883(line=68, offs=38) -- 2469(line=87, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1894(line=70, offs=6) -- 1900(line=70, offs=12)
*/
/*
ATSINStmpdec(tmpref38) ;
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1911(line=71, offs=6) -- 1915(line=71, offs=10)
*/
/*
ATSINStmpdec(tmpref39) ;
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2155(line=77, offs=29) -- 2170(line=77, offs=44)
*/
ATSINSmove(tmp41, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__to_nng_socket(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2145(line=77, offs=19) -- 2201(line=77, offs=75)
*/
ATSINSmove(tmp40, nng_recv(tmp41, ATSPMVrefarg1(ATSPMVptrof(tmpref38)), ATSPMVrefarg1(ATSPMVptrof(tmpref39)), ATSPMVextval(NNG_FLAG_ALLOC))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2228(line=78, offs=27) -- 2235(line=78, offs=34)
*/
ATSINSmove(tmp43, PMVtmpltcst(eq_g0int_int<S2Eextkind(atstype_int)>)(tmp40, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2213(line=78, offs=12) -- 2268(line=78, offs=67)
*/
ATSINSmove_void(tmp42, atspre_assert_errmsg_bool0(tmp43, ATSPMVstring("trans_recv (nanomsg) failed."))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2308(line=80, offs=38) -- 2317(line=80, offs=47)
*/
ATSINSmove(tmp45, atspre_g1uint2int_size_int(tmpref39)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2283(line=80, offs=13) -- 2318(line=80, offs=48)
*/
ATSINSmove(tmp44, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_json_056_sats__json_loadb(tmpref38, tmp45)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2424(line=83, offs=10) -- 2452(line=83, offs=38)
*/
ATSINSmove_void(tmp46, nng_free(tmpref38, tmpref39)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2461(line=86, offs=2) -- 2465(line=86, offs=6)
*/
ATSINSmove(tmpret37, tmp44) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 1883(line=68, offs=38) -- 2469(line=87, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret37) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_recv__12] */
#endif // end of [TEMPLATE]

/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 2548(line=93, offs=27) -- 3151(line=111, offs=4)
*/
/*
local: 
global: trans_nn_broker$13$0(level=0)
local: 
global: 
*/
ATSextern()
postiats_tyrec_0
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_nn_broker(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret47, postiats_tyrec_0) ;
ATStmpdec(tmpref48, nng_socket) ;
ATStmpdec(tmp49, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp50) ;
ATStmpdec(tmp51, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp56, nng_socket) ;
ATStmpdec(tmp57, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp58) ;
ATStmpdec(tmp59, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp62, pthread_t) ;
ATStmpdec(tmp64, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2532(line=93, offs=11) -- 3151(line=111, offs=4)
*/
ATSINSflab(__patsflab_trans_nn_broker):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2557(line=93, offs=36) -- 3151(line=111, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2567(line=94, offs=6) -- 2571(line=94, offs=10)
*/
/*
ATSINStmpdec(tmpref48) ;
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2708(line=98, offs=12) -- 2730(line=98, offs=34)
*/
ATSINSmove(tmp49, nng_bus0_open_raw(ATSPMVrefarg1(ATSPMVptrof(tmpref48)))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2757(line=99, offs=27) -- 2764(line=99, offs=34)
*/
ATSINSmove(tmp51, ATSLIB_056_prelude__eq_g0int_int__14__1(tmp49, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2742(line=99, offs=12) -- 2802(line=99, offs=72)
*/
ATSINSmove_void(tmp50, atspre_assert_errmsg_bool0(tmp51, ATSPMVstring("trans_nn_broker (nanomsg) failed."))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2815(line=100, offs=13) -- 2819(line=100, offs=17)
*/
ATSINSmove(tmp56, tmpref48) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2846(line=103, offs=12) -- 2893(line=103, offs=59)
*/
ATSINSmove(tmp57, ATSextfcall(nng_listen, (tmp56, arg0, ATSPMVi0nt(0), ATSPMVi0nt(0)))) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2920(line=104, offs=27) -- 2927(line=104, offs=34)
*/
ATSINSmove(tmp59, ATSLIB_056_prelude__eq_g0int_int__14__2(tmp57, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2905(line=104, offs=12) -- 2965(line=104, offs=72)
*/
ATSINSmove_void(tmp58, atspre_assert_errmsg_bool0(tmp59, ATSPMVstring("trans_nn_broker (nanomsg) failed."))) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 3045(line=108, offs=12) -- 3114(line=108, offs=81)
*/
ATSINSmove(tmp62, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_thread_056_sats__thread_spawn(ATSPMVcfunlab(1, __patsfun_19, (tmp56, ATSPMVextval(empty))))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 3126(line=110, offs=8) -- 3146(line=110, offs=28)
*/
ATSINSmove(tmp64, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__from_nng_socket(tmp56)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 3120(line=110, offs=2) -- 3147(line=110, offs=29)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret47, postiats_tyrec_0, atslab__0, tmp62) ;
ATSINSstore_fltrec_ofs(tmpret47, postiats_tyrec_0, atslab__1, tmp64) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 2557(line=93, offs=36) -- 3151(line=111, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret47) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_sats__trans_nn_broker] */

#if(0)
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$14$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4638)
tmparg = S2Evar(tk(4638))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret52, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp53, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp53, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4638))>)(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret52, PMVtmpltcst(g0int_eq<S2Evar(tk(4638))>)(arg0, tmp53)) ;

ATSfunbody_end()
ATSreturn(tmpret52) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__14] */
#endif // end of [TEMPLATE]

/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$14$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4638)
tmparg = S2Evar(tk(4638))
tmpsub = Some(tk(4638) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret52__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp53__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp53__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret52__1, atspre_g0int_eq_int(arg0, tmp53__1)) ;

ATSfunbody_end()
ATSreturn(tmpret52__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__14__1] */

/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$14$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4638)
tmparg = S2Evar(tk(4638))
tmpsub = Some(tk(4638) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__14__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret52__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp53__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp53__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret52__2, atspre_g0int_eq_int(arg0, tmp53__2)) ;

ATSfunbody_end()
ATSreturn(tmpret52__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__14__2] */

/*
/Users/hwwu/Git/ats-sessions/ats/transport.dats: 3059(line=108, offs=26) -- 3113(line=108, offs=80)
*/
/*
local: 
global: __patsfun_19$0(level=1)
local: sock$4771(1)(HSEs2exp(S2Eextype(nng_socket))), empty$4773(1)(HSEs2exp(S2Eextype(nng_socket)))
global: sock$4771(1)(HSEs2exp(S2Eextype(nng_socket))), empty$4773(1)(HSEs2exp(S2Eextype(nng_socket)))
*/
ATSstatic()
atsvoid_t0ype
__patsfun_19(nng_socket env0, nng_socket env1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret63) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 3059(line=108, offs=26) -- 3113(line=108, offs=80)
*/
ATSINSflab(__patsflab___patsfun_19):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/transport.dats: 3070(line=108, offs=37) -- 3113(line=108, offs=80)
*/
ATSINSmove_void(tmpret63, ATSextfcall(nng_device, (env0, env1))) ;
ATSfunbody_end()
ATSreturn_void(tmpret63) ;
} /* end of [__patsfun_19] */

#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_transport_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/* in of [local] */
/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]

/* ****** ****** */

/* end-of-compilation-unit */
