/*
**
** The C code is generated by [ATS/Postiats-0-3-12]
** The starting compilation time is: 2018-7-12: 16h:37m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/basics.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/string.dats: 1631(line=50, offs=1) -- 1670(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1629(line=50, offs=1) -- 1668(line=50, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/strptr.dats: 1691(line=54, offs=1) -- 1738(line=54, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1607(line=49, offs=1) -- 1646(line=50, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1669(line=54, offs=1) -- 1715(line=55, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1738(line=59, offs=1) -- 1783(line=60, offs=38)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 1865(line=66, offs=1) -- 1912(line=66, offs=48)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/filebas.dats: 15937(line=927, offs=1) -- 15974(line=928, offs=30)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/array.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/SHARE/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/uuid.dats: 85(line=6, offs=1) -- 134(line=9, offs=3)
*/
ATSextcode_beg()
#include <uuid/uuid.h>
#include <stdlib.h>
ATSextcode_end()
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_assert_errmsg_bool0)
ATSdyncst_mac(atspre_gt_ptr0_ptr0)
ATSdyncst_mac(the_atsptr_null)
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__uuid_alloc, (), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(uuid_generate)
ATSdyncst_mac(uuid_copy)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(uuid_compare)
ATSdyncst_mac(uuid_parse)
ATSdyncst_mac(uuid_unparse)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
/*
/Users/hwwu/Git/ats-sessions/ats/uuid.dats: 136(line=11, offs=1) -- 294(line=22, offs=3)
*/
ATSextcode_beg()

unsigned char* uuid_alloc() {
	unsigned char* ptr = (unsigned char*)malloc(sizeof(uuid_t));
	return ptr;
}

void uuid_free(uuid_t ptr) {
	free(ptr);
}

ATSextcode_end()
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__uuid_alloc() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_generate() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_copy(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_equal(atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_free(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_parse(atsrefarg1_type(atstyarr_type(atstkind_t0ype(atstype_char)))) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_unparse(atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg1_type(atstyarr_type(atstkind_t0ype(atstype_char)))) ;
#endif // end of [QUALIFIED]

/*
/Users/hwwu/Git/ats-sessions/ats/uuid.dats: 718(line=35, offs=22) -- 880(line=40, offs=4)
*/
/*
local: 
global: uuid_alloc$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__uuid_alloc()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp2) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 707(line=35, offs=11) -- 880(line=40, offs=4)
*/
ATSINSflab(__patsflab_uuid_alloc):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 723(line=35, offs=27) -- 880(line=40, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 740(line=36, offs=13) -- 770(line=36, offs=43)
*/
ATSINSmove(tmp1, ATSextfcall(uuid_alloc, ())) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 795(line=37, offs=25) -- 839(line=37, offs=69)
*/
ATSINSmove(tmp3, atspre_gt_ptr0_ptr0(ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp1)), the_atsptr_null)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 780(line=37, offs=10) -- 865(line=37, offs=95)
*/
ATSINSmove_void(tmp2, atspre_assert_errmsg_bool0(tmp3, ATSPMVstring("uuid_generate failed."))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 871(line=39, offs=2) -- 875(line=39, offs=6)
*/
ATSINSmove(tmpret0, tmp1) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 723(line=35, offs=27) -- 880(line=40, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__uuid_alloc] */

/*
/Users/hwwu/Git/ats-sessions/ats/uuid.dats: 941(line=44, offs=25) -- 1014(line=49, offs=4)
*/
/*
local: 
global: uuid_generate$1$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_generate()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp5, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp6) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 927(line=44, offs=11) -- 1014(line=49, offs=4)
*/
ATSINSflab(__patsflab_uuid_generate):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 946(line=44, offs=30) -- 1014(line=49, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 963(line=45, offs=13) -- 976(line=45, offs=26)
*/
ATSINSmove(tmp5, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__uuid_alloc()) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 986(line=46, offs=10) -- 1000(line=46, offs=24)
*/
ATSINSmove_void(tmp6, uuid_generate(ATSPMVrefarg0(tmp5))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1005(line=48, offs=2) -- 1009(line=48, offs=6)
*/
ATSINSmove(tmpret4, tmp5) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 946(line=44, offs=30) -- 1014(line=49, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret4) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_generate] */

/*
/Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1036(line=51, offs=21) -- 1122(line=56, offs=4)
*/
/*
local: 
global: uuid_copy$2$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_copy(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp8, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp9) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1026(line=51, offs=11) -- 1122(line=56, offs=4)
*/
ATSINSflab(__patsflab_uuid_copy):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1044(line=51, offs=29) -- 1122(line=56, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1063(line=52, offs=15) -- 1076(line=52, offs=28)
*/
ATSINSmove(tmp8, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__uuid_alloc()) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1086(line=53, offs=10) -- 1105(line=53, offs=29)
*/
ATSINSmove_void(tmp9, uuid_copy(ATSPMVrefarg0(tmp8), ATSPMVrefarg0(arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1111(line=55, offs=2) -- 1117(line=55, offs=8)
*/
ATSINSmove(tmpret7, tmp8) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1044(line=51, offs=29) -- 1122(line=56, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_copy] */

/*
/Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1145(line=58, offs=22) -- 1256(line=62, offs=4)
*/
/*
local: 
global: uuid_equal$3$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_bool)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_equal(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1134(line=58, offs=11) -- 1256(line=62, offs=4)
*/
ATSINSflab(__patsflab_uuid_equal):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1154(line=58, offs=31) -- 1256(line=62, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1229(line=61, offs=2) -- 1248(line=61, offs=21)
*/
ATSINSmove(tmp15, uuid_compare(ATSPMVrefarg0(arg0), ATSPMVrefarg0(arg1))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1229(line=61, offs=2) -- 1252(line=61, offs=25)
*/
ATSINSmove(tmpret10, ATSLIB_056_prelude__eq_g0int_int__4__1(tmp15, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1154(line=58, offs=31) -- 1256(line=62, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret10) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_equal] */

#if(0)
/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$4$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4624)
tmparg = S2Evar(tk(4624))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp12, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4624))>)(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret11, PMVtmpltcst(g0int_eq<S2Evar(tk(4624))>)(arg0, tmp12)) ;

ATSfunbody_end()
ATSreturn(tmpret11) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__4] */
#endif // end of [TEMPLATE]

/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$4$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4624)
tmparg = S2Evar(tk(4624))
tmpsub = Some(tk(4624) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp12__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret11__1, atspre_g0int_eq_int(arg0, tmp12__1)) ;

ATSfunbody_end()
ATSreturn(tmpret11__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__4__1] */

/*
/Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1278(line=64, offs=21) -- 1347(line=65, offs=60)
*/
/*
local: 
global: uuid_free$8$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_free(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret16) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1268(line=64, offs=11) -- 1347(line=65, offs=60)
*/
ATSINSflab(__patsflab_uuid_free):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1289(line=65, offs=2) -- 1347(line=65, offs=60)
*/
ATSINSmove_void(tmpret16, ATSextfcall(uuid_free, (ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), arg0)))) ;
ATSfunbody_end()
ATSreturn_void(tmpret16) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_free] */

/*
/Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1370(line=67, offs=22) -- 1507(line=73, offs=4)
*/
/*
local: 
global: uuid_parse$9$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_parse(atsrefarg1_type(atstyarr_type(atstkind_t0ype(atstype_char))) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret17, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp18, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp20) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1359(line=67, offs=11) -- 1507(line=73, offs=4)
*/
ATSINSflab(__patsflab_uuid_parse):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1378(line=67, offs=30) -- 1507(line=73, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1395(line=68, offs=13) -- 1408(line=68, offs=26)
*/
ATSINSmove(tmp18, _057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__uuid_alloc()) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1420(line=69, offs=12) -- 1438(line=69, offs=30)
*/
ATSINSmove(tmp19, uuid_parse(ATSPMVrefarg1(arg0), ATSPMVrefarg0(tmp18))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1463(line=70, offs=25) -- 1470(line=70, offs=32)
*/
ATSINSmove(tmp21, ATSLIB_056_prelude__eq_g0int_int__4__2(tmp19, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1448(line=70, offs=10) -- 1493(line=70, offs=55)
*/
ATSINSmove_void(tmp20, atspre_assert_errmsg_bool0(tmp21, ATSPMVstring("uuid_parse failed."))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1499(line=72, offs=2) -- 1503(line=72, offs=6)
*/
ATSINSmove(tmpret17, tmp18) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1378(line=67, offs=30) -- 1507(line=73, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret17) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_parse] */

/*
/Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$4$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4624)
tmparg = S2Evar(tk(4624))
tmpsub = Some(tk(4624) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__4__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp12__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Programs/atsgit/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret11__2, atspre_g0int_eq_int(arg0, tmp12__2)) ;

ATSfunbody_end()
ATSreturn(tmpret11__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__4__2] */

/*
/Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1532(line=75, offs=24) -- 1566(line=75, offs=58)
*/
/*
local: 
global: uuid_unparse$11$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_unparse(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg1_type(atstyarr_type(atstkind_t0ype(atstype_char))) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret24) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1519(line=75, offs=11) -- 1566(line=75, offs=58)
*/
ATSINSflab(__patsflab_uuid_unparse):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-sessions/ats/uuid.dats: 1546(line=75, offs=38) -- 1566(line=75, offs=58)
*/
ATSINSmove_void(tmpret24, uuid_unparse(ATSPMVrefarg0(arg0), ATSPMVrefarg1(arg1))) ;

ATSfunbody_end()
ATSreturn_void(tmpret24) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_sats__uuid_unparse] */

#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_hwwu_057_Git_057_ats_055_sessions_057_ats_057_uuid_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/* in of [local] */
/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]

/* ****** ****** */

/* end-of-compilation-unit */
